development:
  adapter: redis
  url: redis://redis:6379/1
  channel_prefix: ikuji_app_development

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV["REDIS_URL"] %>
  channel_prefix: ikuji_app_production